/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.exercise.login_complesso;

/**
 *
 * @author Lorenzo
 */
public class DialogNegato extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogNegato.class.getName());
    private MainFrame mainframe;

    /**
     * Creates new form DialogNegato
     */
    public DialogNegato(MainFrame mainframe, boolean modal) {
        super(mainframe, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.mainframe = mainframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_invio = new javax.swing.JButton();
        txt_campoNegato = new javax.swing.JTextField();
        lbl_campoNegato = new javax.swing.JLabel();
        lbl_titolo = new javax.swing.JLabel();
        lbl_errore = new javax.swing.JLabel();
        btn_indietro = new javax.swing.JButton();
        pwd_campoNegato = new javax.swing.JPasswordField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(385, 250));
        getContentPane().setLayout(null);

        btn_invio.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_invio.setText("INVIO");
        btn_invio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        btn_invio.addActionListener(this::btn_invioActionPerformed);
        getContentPane().add(btn_invio);
        btn_invio.setBounds(62, 118, 73, 39);

        txt_campoNegato.setBackground(java.awt.Color.yellow);
        txt_campoNegato.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        txt_campoNegato.setToolTipText("");
        txt_campoNegato.setRequestFocusEnabled(false);
        txt_campoNegato.addActionListener(this::txt_campoNegatoActionPerformed);
        getContentPane().add(txt_campoNegato);
        txt_campoNegato.setBounds(110, 80, 250, 30);

        lbl_campoNegato.setFont(new java.awt.Font("Microsoft YaHei", 2, 14)); // NOI18N
        lbl_campoNegato.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_campoNegato.setText("Nome:");
        getContentPane().add(lbl_campoNegato);
        lbl_campoNegato.setBounds(8, 88, 97, 22);

        lbl_titolo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lbl_titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titolo.setText("ACCESSO NEGATO");
        getContentPane().add(lbl_titolo);
        lbl_titolo.setBounds(6, 6, 358, 35);

        lbl_errore.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        lbl_errore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_errore.setText("Non hai inserito il nome");
        getContentPane().add(lbl_errore);
        lbl_errore.setBounds(20, 47, 333, 33);

        btn_indietro.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_indietro.setText("ESC");
        btn_indietro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        btn_indietro.addActionListener(this::btn_indietroActionPerformed);
        getContentPane().add(btn_indietro);
        btn_indietro.setBounds(255, 120, 73, 39);

        pwd_campoNegato.setBackground(java.awt.Color.yellow);
        pwd_campoNegato.setPreferredSize(new java.awt.Dimension(64, 26));
        getContentPane().add(pwd_campoNegato);
        pwd_campoNegato.setBounds(110, 82, 250, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_invioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invioActionPerformed
       if("Nome:".equals(lbl_campoNegato.getText())){
        mainframe.setNome(txt_campoNegato.getText());
        
       }
       if("Cognome:".equals(lbl_campoNegato.getText())){
        mainframe.setCognome(txt_campoNegato.getText());
       }
       if("Password:".equals(lbl_campoNegato.getText())){
        mainframe.setPassword(pwd_campoNegato.getText());
       }
       txt_campoNegato.setText("");
       pwd_campoNegato.setText("");
       dispose();
    }//GEN-LAST:event_btn_invioActionPerformed

    private void btn_indietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_indietroActionPerformed
        dispose();
    }//GEN-LAST:event_btn_indietroActionPerformed

    private void txt_campoNegatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_campoNegatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_campoNegatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogNegato dialog = new DialogNegato(new MainFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_indietro;
    private javax.swing.JButton btn_invio;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel lbl_campoNegato;
    public javax.swing.JLabel lbl_errore;
    private javax.swing.JLabel lbl_titolo;
    public javax.swing.JPasswordField pwd_campoNegato;
    public javax.swing.JTextField txt_campoNegato;
    // End of variables declaration//GEN-END:variables
}
