/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exercise.login_complesso;

/**
 *
 * @author Lorenzo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    String varNome = "Lorenzo";
    String varCognome = "Tabolacci";
    String varPassword = "12345678";
    
    public void setNome(String nome) {
    txt_nome.setText(nome);
    }
    public void setCognome(String cognome) {
    txt_cognome.setText(cognome);
    }

    public void setPassword(String password) {
        txt_password.setText(password);
    }
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        pnl_login = new javax.swing.JPanel();
        lbl_login = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_cognome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_cognome = new javax.swing.JTextField();
        lbl_cognome1 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_esc = new javax.swing.JButton();
        btn_accedi = new javax.swing.JButton();
        btn_hint = new javax.swing.JButton();

        lbl_nome1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_nome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nome1.setText("Nome:");
        lbl_nome1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_nome1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_nome1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        pnl_login.setBackground(java.awt.Color.lightGray);
        pnl_login.setBorder(new javax.swing.border.LineBorder(java.awt.Color.blue, 8, true));
        pnl_login.setForeground(java.awt.Color.gray);
        pnl_login.setToolTipText("");
        pnl_login.setName(""); // NOI18N
        pnl_login.setOpaque(false);

        lbl_login.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login.setText("LOGIN");
        lbl_login.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_nome.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_nome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_nome.setText("Nome:");
        lbl_nome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_nome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_nome.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbl_cognome.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_cognome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_cognome.setText("Cognome:");
        lbl_cognome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_cognome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txt_nome.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_nome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nome.setToolTipText("Inserisci il nome");
        txt_nome.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        txt_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nomeFocusGained(evt);
            }
        });
        txt_nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nomeMouseClicked(evt);
            }
        });
        txt_nome.addActionListener(this::txt_nomeActionPerformed);

        txt_cognome.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_cognome.setToolTipText("Inserisci il cognome");
        txt_cognome.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));

        lbl_cognome1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_cognome1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_cognome1.setText("Password:");
        lbl_cognome1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_cognome1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_cognome1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txt_password.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_password.setToolTipText("Inserisci la password");
        txt_password.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));

        btn_esc.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_esc.setText("ESC");
        btn_esc.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.cyan));
        btn_esc.addActionListener(this::btn_escActionPerformed);

        btn_accedi.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_accedi.setText("ACCEDI");
        btn_accedi.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.cyan));
        btn_accedi.addActionListener(this::btn_accediActionPerformed);

        btn_hint.setIcon(new javax.swing.ImageIcon("C:\\Users\\utente\\Downloads\\lightbulb_48x48.png")); // NOI18N
        btn_hint.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.cyan));
        btn_hint.addActionListener(this::btn_hintActionPerformed);

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_loginLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cognome1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_accedi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_loginLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(btn_hint, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_esc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_login)
                .addGap(26, 26, 26)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nome))
                .addGap(12, 12, 12)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cognome))
                .addGap(18, 18, 18)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cognome1))
                .addGap(28, 28, 28)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_accedi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_esc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        txt_nome.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        txt_nome.setText("");
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void btn_accediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accediActionPerformed
        DialogNegato accessoNegato = new DialogNegato(this,true);
        
        if (txt_nome.getText().isBlank()) { 
            accessoNegato.lbl_errore.setText("Non hai inserito il nome");
            accessoNegato.lbl_campoNegato.setText("Nome:");  
            accessoNegato.txt_campoNegato.setVisible(true);
            accessoNegato.pwd_campoNegato.setVisible(false);
            accessoNegato.setVisible(true);
        }
        if (txt_cognome.getText().isBlank()){
            accessoNegato.lbl_errore.setText("Non hai inserito il cognome");
            accessoNegato.lbl_campoNegato.setText("Cognome:");
            accessoNegato.txt_campoNegato.setVisible(true);
            accessoNegato.pwd_campoNegato.setVisible(false);
            accessoNegato.setVisible(true);
            
        }
        if (txt_password.getText().isBlank()){
            accessoNegato.lbl_errore.setText("Non hai inserito la password");
            accessoNegato.lbl_campoNegato.setText("Password:");
            accessoNegato.txt_campoNegato.setVisible(false);
            accessoNegato.pwd_campoNegato.setVisible(true);
            accessoNegato.setVisible(true);
            
        }
        
        if (txt_nome.getText().equals(varNome) && txt_cognome.getText().equals(varCognome) && txt_password.getText().equals(varPassword)){
            IO.println("Stai entrando...");
        }
        
        
        
        
        
    }//GEN-LAST:event_btn_accediActionPerformed

    private void btn_escActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escActionPerformed
        dispose();
    }//GEN-LAST:event_btn_escActionPerformed

    private void btn_hintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hintActionPerformed
        Hint hint = new Hint(this,true);
        hint.setVisible(true);
    }//GEN-LAST:event_btn_hintActionPerformed

    private void txt_nomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nomeMouseClicked
        txt_nome.setText("");
    }//GEN-LAST:event_txt_nomeMouseClicked

    private void txt_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusGained
        txt_nome.setText("");
    }//GEN-LAST:event_txt_nomeFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accedi;
    private javax.swing.JButton btn_esc;
    private javax.swing.JButton btn_hint;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_cognome;
    private javax.swing.JLabel lbl_cognome1;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_nome1;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JTextField txt_cognome;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
