/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package md.gui;

/**
 *
 * @author margh
 */
public class TabFrm extends javax.swing.JFrame {

    /**
     * Creates new form TabFrm
     */
    public TabFrm() {
        initComponents();
        //
        /*
        cb_citta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selezionare una città", "Palermo", "Catania", "Messina"}));
        
        cb_citta.addItem("Trapani");
        */
        /*
        cb_citta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selezionare un numero"}));
        for (int i = 1; i <= 31; i++) {
            cb_citta.addItem(String.valueOf(i));
        }
        
        cb_citta.removeItemAt(3);
        
        System.out.println (cb_citta.getItemCount());
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_titolo1 = new javax.swing.JLabel();
        txt_Prova = new javax.swing.JTextField();
        btn_cambioTab = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_titolo2 = new javax.swing.JLabel();
        rb_s2 = new javax.swing.JRadioButton();
        rb_s1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_titolo3 = new javax.swing.JLabel();
        cb_citta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titolo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_titolo1.setText("Questa è la prima scheda");

        txt_Prova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProvaActionPerformed(evt);
            }
        });

        btn_cambioTab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cambioTab.setText("Cambio Tab");
        btn_cambioTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbl_titolo1)
                        .addGap(47, 47, 47)
                        .addComponent(txt_Prova, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btn_cambioTab, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titolo1)
                    .addComponent(txt_Prova, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btn_cambioTab)
                .addGap(122, 122, 122))
        );

        jTabbedPane1.addTab("Primo", jPanel1);

        lbl_titolo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_titolo2.setText("Questa è la seconda scheda");

        buttonGroup1.add(rb_s2);
        rb_s2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb_s2.setText("Scelta 2");
        rb_s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_s2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_s1);
        rb_s1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb_s1.setText("Scelta 1");
        rb_s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_s1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbl_titolo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(rb_s1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_s2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(269, 269, 269))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titolo2)
                    .addComponent(rb_s1))
                .addGap(14, 14, 14)
                .addComponent(rb_s2)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Secondo", jPanel2);

        lbl_titolo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_titolo3.setText("Questa è la terza scheda");

        cb_citta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selezionare una città", "Torino", "Alessandria", "Asti", "Biella", "Cuneo", "Novara", "Verbania-Cusio-Ossola", "Vercelli" }));
        cb_citta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cittaActionPerformed(evt);
            }
        });

        jLabel1.setText("Selezionare una città:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuneo", "Novara", "Torino" }));
        jComboBox1.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_citta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_titolo3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_titolo3)
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_citta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(60, 60, 60)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Terzo", jPanel3);
        jTabbedPane1.addTab("Questa è la quarta linguetta", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_cittaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cittaActionPerformed

    }//GEN-LAST:event_cb_cittaActionPerformed

    private void rb_s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_s1ActionPerformed

    private void rb_s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_s2ActionPerformed

    private void btn_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambioActionPerformed
        // TODO add your handling code here:
        //jTabbedPane1.setMnemonicAt();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btn_cambioActionPerformed

    private void txt_ProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambioTab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_citta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_titolo1;
    private javax.swing.JLabel lbl_titolo2;
    private javax.swing.JLabel lbl_titolo3;
    private javax.swing.JRadioButton rb_s1;
    private javax.swing.JRadioButton rb_s2;
    private javax.swing.JTextField txt_Prova;
    // End of variables declaration//GEN-END:variables
}
