/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package md.gui;
import java.io.*; 
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author margh
 */
public class TableFrm extends javax.swing.JFrame {

    /**
     * Creates new form TableFrm
     */
    public TableFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        //inizializza_tabella();
    }

    void inizializza_tabella () {
        
        // Metodo statico
        jTab_Cli.setModel(new javax.swing.table.DefaultTableModel(
            
            new Object [][] {
                {"Luca", "Rizzo", "statico1", "citta1"},
                {"Nicola", "cognome2", "statico2", "citta2"},
                {"Roberta", "cognome3", "statico3", "citta3"}
            },
            new String [] {"Nome Intestazione", "Cognome", "Tipologia", "Città"}
        ));
        jScrollPane2.setViewportView(jTab_Cli); 
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTab_Cli = new javax.swing.JTable();
        btn_TabStatica = new javax.swing.JButton();
        btn_Ricerca = new javax.swing.JButton();
        btn_TabDinamica1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTab_Cli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTab_Cli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Qui", "Rossi",  new Integer(20100), "Paperopoli"},
                {"Quo", "Gialli",  new Integer(20101), "Paperopoli"},
                {"Qua", "Verdi",  new Integer(20102), null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Colonna 1", "Colonna 2", "Colonna 3", "Colonna 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTab_Cli.setToolTipText("");
        jTab_Cli.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTab_Cli);

        btn_TabStatica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TabStatica.setText("Modo Statico");
        btn_TabStatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TabStaticaActionPerformed(evt);
            }
        });

        btn_Ricerca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Ricerca.setText("Ricerca");
        btn_Ricerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RicercaActionPerformed(evt);
            }
        });

        btn_TabDinamica1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TabDinamica1.setText("Dinamico");
        btn_TabDinamica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TabDinamica1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cognome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Città:");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(125, 125, 125)
                .addComponent(btn_TabStatica, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btn_TabDinamica1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btn_Ricerca, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Ricerca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TabStatica, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TabDinamica1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TabStaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TabStaticaActionPerformed
        // TODO add your handling code here:
        
           // Secondo metodo statico con array, ricopre il modello
           String[][] var_dati = {
            { "Massimiliano", "Rossi", "statico da bottone", "Torino" },
            { "Antonio", "Verdi", "statico da bottone", "Il Cairo" },
           };
           
           String[] var_intestazione = {"Nome", "Cognome", "Metodo inserimento", "Città"};
           
           // setModel imposta il modello della tabella, passando come dati 
           // l'array bidimensinale per i dati di dettaglio
           // l'array monodimensionale per l'intestazione (che avrebbe potuto essere una costante esterna)
           jTab_Cli.setModel(new DefaultTableModel(var_dati, var_intestazione));
           
           /*
           // Terzo metodo statico con addrow, riutilizza lo stesso modello impostato in inizializzazione
           DefaultTableModel model = (DefaultTableModel) jTab_Cli.getModel();
           model.setRowCount(0);
           model.setColumnIdentifiers(new Object[]{"Nome (statico3)", "Cognome (statico3)", "Metodo inserimento (statico3)", "Città (statico3)"});
           model.addRow(new Object[]{"Paolo", "Rossi", "statico da bottone", "Torino"});
           model.addRow(new Object[]{"Stefano", "Verdi", "statico da bottone", "Il Cairo"});
           model.setRowCount(3);
           jTab_Cli.setModel(model);
           */
           
    }//GEN-LAST:event_btn_TabStaticaActionPerformed

    private void btn_RicercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RicercaActionPerformed
        // Filtro sui dati presenti a video
        
    }//GEN-LAST:event_btn_RicercaActionPerformed

    private void btn_TabDinamica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TabDinamica1ActionPerformed
        
        // Metodo dinamico
        DefaultTableModel model = (DefaultTableModel) jTab_Cli.getModel();
               
        //model.setRowCount(0);
        
        model.setColumnIdentifiers(new Object[]{"Nome (din)", "Cognome (din)", "Metodo inserimento (din)", "Città (din)"});
        
        try {
            String riga;
            
            BufferedReader file_lettura = new BufferedReader(new FileReader("C:\\Users\\margh\\Documents\\NetBeansProjects\\GUI\\clientiCAP.txt"));
              
            while((riga = file_lettura.readLine()) != null) {
                
                //if  campo di ricerca
                model.addRow(riga.split(";"));
            }
            
            /*riga = file_lettura.readLine();
            
            while(riga != null) {
                model.addRow(riga.split(";"));
                
                riga = file_lettura.readLine();
            }
            */
            /* alternativa con do while
            do {
                riga = file_lettura.readLine();
                
                if (riga != null) {
                    model.addRow(riga.split(";"));
                }

            } while(riga != null);
            */
            file_lettura.close(); 
        } 
        catch(IOException e){
            System.out.println(e);
        } catch(Exception e){
            System.out.println(e);
        }        
        
        //model.setRowCount(25);
        
        jTab_Cli.setModel(model);

    }//GEN-LAST:event_btn_TabDinamica1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        System.out.println(jTab_Cli.getModel().getValueAt(0, 1));
        System.out.println(jTab_Cli.getModel().getValueAt(0, 2));
        System.out.println(jTab_Cli.getModel().getValueAt(0, 3));
        
        // aggiunge righe vuote alla tabella
        DefaultTableModel model = (DefaultTableModel) jTab_Cli.getModel();
        String [] mio = {};
        model.addRow(mio);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTab_Cli.getModel();
        //String [] mio = {};
        //model.setRowCount(0);
        //jTab_Cli.selectAll();// .removeColumnSelectionInterval(2, 3);
        //jTab_Cli.addColumnSelectionInterval(0, 2);
        jTab_Cli.removeColumnSelectionInterval(1, 2);
        System.out.println(jTab_Cli.getColumnSelectionAllowed());
        
        //model.;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ricerca;
    private javax.swing.JButton btn_TabDinamica1;
    private javax.swing.JButton btn_TabStatica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTab_Cli;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}