/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package md.gui;



/**
 *
 * @author margh
 */
public class FramePrinc extends javax.swing.JFrame {

    /**
     * Creates new form FramePrinc
     */
    public FramePrinc() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_nome.setText("<HTML><u>Nome</u>:</HTML>");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbg_Sit_Fiscale = new javax.swing.ButtonGroup();
        pnl_nominativo = new javax.swing.JPanel();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_cognome = new javax.swing.JTextField();
        lbl_cognome = new javax.swing.JLabel();
        rb_giuridica = new javax.swing.JRadioButton();
        rb_fisica = new javax.swing.JRadioButton();
        pnl_bottoni = new javax.swing.JPanel();
        btn_esc = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        lbl_titolo = new javax.swing.JLabel();
        pnl_residenza1 = new javax.swing.JPanel();
        lbl_Indirizzo1 = new javax.swing.JLabel();
        txt_Indirizzo1 = new javax.swing.JTextField();
        txt_Cap1 = new javax.swing.JTextField();
        txt_Citta1 = new javax.swing.JTextField();
        lbl_citta1 = new javax.swing.JLabel();
        lbl_cap1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Anagrafica Cliente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        lbl_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nome.setText("Nome:");

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        txt_cognome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cognomeActionPerformed(evt);
            }
        });

        lbl_cognome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cognome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cognome.setText("Cognome:");

        rbg_Sit_Fiscale.add(rb_giuridica);
        rb_giuridica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_giuridica.setMnemonic('1');
        rb_giuridica.setSelected(true);
        rb_giuridica.setText("Persona Giuridica");
        rb_giuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_giuridicaActionPerformed(evt);
            }
        });

        rbg_Sit_Fiscale.add(rb_fisica);
        rb_fisica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_fisica.setMnemonic('2');
        rb_fisica.setText("Persona Fisica");
        rb_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_fisicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_nominativoLayout = new javax.swing.GroupLayout(pnl_nominativo);
        pnl_nominativo.setLayout(pnl_nominativoLayout);
        pnl_nominativoLayout.setHorizontalGroup(
            pnl_nominativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_nominativoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_nominativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_nominativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_nominativoLayout.createSequentialGroup()
                        .addComponent(rb_giuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(rb_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_nominativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nome)
                        .addComponent(txt_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnl_nominativoLayout.setVerticalGroup(
            pnl_nominativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_nominativoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_nominativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_nominativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnl_nominativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_giuridica)
                    .addComponent(rb_fisica))
                .addContainerGap())
        );

        btn_esc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_esc.setText("ESCI");
        btn_esc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_esc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escActionPerformed(evt);
            }
        });

        btn_ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ok.setText("OK");
        btn_ok.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_bottoniLayout = new javax.swing.GroupLayout(pnl_bottoni);
        pnl_bottoni.setLayout(pnl_bottoniLayout);
        pnl_bottoniLayout.setHorizontalGroup(
            pnl_bottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bottoniLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btn_esc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        pnl_bottoniLayout.setVerticalGroup(
            pnl_bottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bottoniLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_bottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_esc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lbl_titolo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_titolo.setText("Inserire dati cliente");

        pnl_residenza1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Residenza  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        lbl_Indirizzo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Indirizzo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Indirizzo1.setText("Indirizzo:");

        txt_Indirizzo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Indirizzo1.setForeground(new java.awt.Color(204, 204, 204));
        txt_Indirizzo1.setText("Inserire indirizzo");
        txt_Indirizzo1.setToolTipText("");
        txt_Indirizzo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Indirizzo1ActionPerformed(evt);
            }
        });

        txt_Cap1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Cap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cap1ActionPerformed(evt);
            }
        });

        txt_Citta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Citta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Citta1ActionPerformed(evt);
            }
        });

        lbl_citta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_citta1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_citta1.setText("Città:");

        lbl_cap1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cap1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cap1.setText("CAP:");

        javax.swing.GroupLayout pnl_residenza1Layout = new javax.swing.GroupLayout(pnl_residenza1);
        pnl_residenza1.setLayout(pnl_residenza1Layout);
        pnl_residenza1Layout.setHorizontalGroup(
            pnl_residenza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_residenza1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_residenza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cap1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Indirizzo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_residenza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_residenza1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Indirizzo1))
                    .addGroup(pnl_residenza1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txt_Cap1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_citta1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Citta1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        pnl_residenza1Layout.setVerticalGroup(
            pnl_residenza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_residenza1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnl_residenza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Indirizzo1)
                    .addComponent(lbl_Indirizzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_residenza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_cap1)
                    .addComponent(txt_Cap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_citta1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Citta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pnl_bottoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_residenza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_nominativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titolo))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_titolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_nominativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pnl_residenza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_bottoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_cognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cognomeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_cognomeActionPerformed

    private void btn_escActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_escActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed

        FinestraDialog finestra = new FinestraDialog(this, true);

        if (txt_nome.getText().isBlank() && txt_cognome.getText().isBlank()  ) { //true && false - false && true - true && true
            finestra.lbl_Titolo.setText("Non hai inserito il nome, birbante!");
        } else {
           finestra.lbl_Titolo.setText("Tutto corretto");
           finestra.txt_Nome_Cognome.setText(txt_nome.getText() + " " + txt_cognome.getText());
        }
        
        finestra.setVisible(true);
        
        System.out.println(rb_giuridica.isSelected());
        System.out.println(rb_fisica.isSelected());

        System.out.println(rbg_Sit_Fiscale.getSelection());

        if (rb_giuridica.getModel() == rbg_Sit_Fiscale.getSelection()) {
            System.out.println("Hai selezionato giuridica");
        } else {
            System.out.println("Hai selezionato persona fisica");
        }
       
        
        
        
        
        
        
        
        
        
        
        
        
        /* esempi per spiegare la set */
        //finestra.txt_Nome_Cognome = "metto la stringa a mio piacere";
        
        //finestra.txt_Nome_Cognome.setText(this.txt_nome.getText());
       
        //finestra.txt_Nome_Cognome.setText("metto la stringa a mio piacere");
        
        //finestra.txt_Nome_Cognome.setText(txt_nome.getText() + " " + txt_cognome.getText());
        
        /*
        if (txt_nome.getText().isBlank() && txt_cognome.getText().isBlank()  ) { //true && false - false && true - true && true
           finestra.lbl_Titolo.setText("Non hai inserito il nome, birbante!");
        } else {
           finestra.lbl_Titolo.setText("Tutto corretto");
           finestra.txt_Nome_Cognome.setText(txt_nome.getText() + " " + txt_cognome.getText());
        }
      
        finestra.setVisible(true);
        
        /*
        if (txt_nome.getText().isEmpty()) { 
           finestra.lbl_Titolo.setText("Non hai inserito il nome, birbante!");
        } else {
           finestra.lbl_Titolo.setText("Tutto corretto");
           finestra.txt_Nome_Cognome.setText(txt_nome.getText() + " " + txt_cognome.getText());
        }
      
        finestra.setVisible(true);
        */
     
        /*
        System.out.println(rb_giuridica.isSelected());
        System.out.println(rb_fisica.isSelected());

        System.out.println(rbg_Sit_Fiscale.getSelection());

        if (rb_giuridica.getModel() == rbg_Sit_Fiscale.getSelection()) {
            System.out.println("giuridica");
        } else {
            System.out.println("fisica");
        }
        */
        
                
    }//GEN-LAST:event_btn_okActionPerformed

    private void rb_giuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_giuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_giuridicaActionPerformed

    private void rb_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_fisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_fisicaActionPerformed

    private void txt_Indirizzo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Indirizzo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Indirizzo1ActionPerformed

    private void txt_Cap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cap1ActionPerformed

    private void txt_Citta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Citta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Citta1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_esc;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel lbl_Indirizzo1;
    private javax.swing.JLabel lbl_cap1;
    private javax.swing.JLabel lbl_citta1;
    private javax.swing.JLabel lbl_cognome;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_titolo;
    private javax.swing.JPanel pnl_bottoni;
    private javax.swing.JPanel pnl_nominativo;
    private javax.swing.JPanel pnl_residenza1;
    private javax.swing.JRadioButton rb_fisica;
    private javax.swing.JRadioButton rb_giuridica;
    private javax.swing.ButtonGroup rbg_Sit_Fiscale;
    private javax.swing.JTextField txt_Cap1;
    private javax.swing.JTextField txt_Citta1;
    private javax.swing.JTextField txt_Indirizzo1;
    private javax.swing.JTextField txt_cognome;
    protected javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}